version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: '${DOCKER_FILE}'
      args:
        - NODE_VERSION=${NODE_VERSION}
    image: '${IMAGE_NAME}'
    container_name: '${CONTAINER_NAME}'
    restart: always
    env_file: .env
    networks:
      - hbsnet
      - mariadb_default
    ports:
      - '${PROD_PORT}:${DEV_PORT}'

networks:
  hbsnet:
    driver: bridge
  mariadb_default:
    external: true
